import { cn } from "@/lib/utils";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";
import TanstackQueryProvider from "@/providers/tanstack-query-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { neobrutalism } from "@clerk/themes";

export const metadata: Metadata = {
  title: "Next Anime | Your anime website preference",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: neobrutalism }}>
      <html lang="en">
        <body
          className={cn(
            "text-background bg-foreground relative",
            GeistSans.className
          )}
        >
          <TanstackQueryProvider>{children}</TanstackQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
