import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import TanstackQueryProvider from "@/providers/tanstack-query-provider";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Anime | Your anime website preference",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "text-background bg-foreground relative",
          GeistSans.className
        )}
      >
        <TanstackQueryProvider>
          {children}
          <Toaster richColors expand />
        </TanstackQueryProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
